/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminBootstrapRouteImport } from './routes/admin-bootstrap'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPulseRouteImport } from './routes/_authenticated/pulse'
import { Route as AuthenticatedMatrixRouteImport } from './routes/_authenticated/matrix'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBootstrapRoute = AdminBootstrapRouteImport.update({
  id: '/admin-bootstrap',
  path: '/admin-bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPulseRoute = AuthenticatedPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMatrixRoute = AuthenticatedMatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-bootstrap': typeof AdminBootstrapRoute
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/matrix': typeof AuthenticatedMatrixRoute
  '/pulse': typeof AuthenticatedPulseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-bootstrap': typeof AdminBootstrapRoute
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/matrix': typeof AuthenticatedMatrixRoute
  '/pulse': typeof AuthenticatedPulseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-bootstrap': typeof AdminBootstrapRoute
  '/auth': typeof AuthRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/matrix': typeof AuthenticatedMatrixRoute
  '/_authenticated/pulse': typeof AuthenticatedPulseRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-bootstrap'
    | '/auth'
    | '/welcome'
    | '/admin'
    | '/calendar'
    | '/goals'
    | '/journal'
    | '/matrix'
    | '/pulse'
    | '/settings'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-bootstrap'
    | '/auth'
    | '/welcome'
    | '/admin'
    | '/calendar'
    | '/goals'
    | '/journal'
    | '/matrix'
    | '/pulse'
    | '/settings'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-bootstrap'
    | '/auth'
    | '/welcome'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/goals'
    | '/_authenticated/journal'
    | '/_authenticated/matrix'
    | '/_authenticated/pulse'
    | '/_authenticated/settings'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminBootstrapRoute: typeof AdminBootstrapRoute
  AuthRoute: typeof AuthRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-bootstrap': {
      id: '/admin-bootstrap'
      path: '/admin-bootstrap'
      fullPath: '/admin-bootstrap'
      preLoaderRoute: typeof AdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pulse': {
      id: '/_authenticated/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof AuthenticatedPulseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matrix': {
      id: '/_authenticated/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof AuthenticatedMatrixRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedMatrixRoute: typeof AuthenticatedMatrixRoute
  AuthenticatedPulseRoute: typeof AuthenticatedPulseRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedMatrixRoute: AuthenticatedMatrixRoute,
  AuthenticatedPulseRoute: AuthenticatedPulseRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminBootstrapRoute: AdminBootstrapRoute,
  AuthRoute: AuthRoute,
  WelcomeRoute: WelcomeRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
